### ISSUE TITLE
Can't press Esc to just close the shop.

### ISSUE THREAD

**Issue by JosEffigy** [ark120202/aabs#12]
It's just annoying and gets in the way.

**Comment by ark120202** [comment]
AFAIK for now there is no way to hook for ESC globally. [Current shop panel properties](https://github.com/ark120202/aabs/blob/a32832a1d32c7fce4d698f1b185b584466af0d10/content/panorama/layout/custom_game/panorama_shop.xml#L48) are similiar to [original](https://github.com/SteamDatabase/GameTracking-Dota2/blob/f331fd6f0c05539bb79f8e7c8b3d4736e06ce2ef/game/dota/pak01_dir/panorama/layout/hud/dota_hud_shop.xml#L20), but it won't work, since oncancel works only for panels in focus. Perhaps it can be something with `$.RegisterForUnhandledEvent()`, but looks like required event is undocumented / not exists. For now closing this as unimplementable.
