### ISSUE TITLE
Freya ult infinity procs in riki ult(custom abil)

### ISSUE THREAD

**Issue by shimaosu** [ark120202/aabs#326]

**Comment by Celireor** [comment]
Tricks don't allow [ApplyModifier](https://github.com/ark120202/angel-arena-black-star/search?q=applymodifier&unscoped_q=applymodifier) or [RemoveModifier](https://github.com/ark120202/angel-arena-black-star/search?q=removemodifier&unscoped_q=removemodifier)

so working as intended (no kadash crit, freya crit dont expire

**Comment by ark120202** [comment]
That's because in datadriven by default all actions that use "Target" field ignore invulnerable units. It's solvable with `DOTA_UNIT_TARGET_FLAG_INVULNERABLE`, example: https://github.com/ark120202/angel-arena-black-star/blob/2ee12141c04a48b9747311ab4e1f9b1215be0deb/game/scripts/npc/items/black_king_bar.txt#L169-L175
