### ISSUE TITLE
Angel Arena black star

### ISSUE THREAD

**Issue by RickuTan2** [ark120202/aabs#485]
What is happening iwth Angel Arena BlackStar,at any mode there are crashesh ALL the itme,cant use skill tree,in middle of the game just crashed. 2nd day already ....

**Comment by ark120202** [comment]
These things were broken in one of latest dota updates. Crashes appeared in all custom games and fixed in an update few days after it. Shop and talent UI were fixed in https://github.com/ark120202/angel-arena-black-star/commit/c1a71f85794e6f99d6e4c40093d872a67e87503e. I'm not actively maintaining aabs now and fix things in my free time, so I don't give any guarantees on fixing time frames.

**Comment by RickuTan2** [comment]
hi thanks,i noticed that when somebody change hero at MK game crashes as well.








 >-------- Оригинално писмо --------

 >От: ark120202 notifications@github.com

 >Относно: Re: [ark120202/angel-arena-black-star] Angel Arena black star (#485)

 >До: ark120202/angel-arena-black-star  

 >Изпратено на: 12.06.2019 06:10



 
 
  
Closed  #485 .
