### ISSUE TITLE
Вопрос по кликбаю

### ISSUE THREAD

**Issue by rebradoniera** [ark120202/aabs#65]
Вопрос , будет ли исправлена покупка предметов в кликбае ? А то закупает с задержкой+ не работает кнопка быстрой покупки , или это механика?
  Предметы в панели быстрой закупки покупаются с задержкой (примерно секунда ) , и нельзя закупать предметы из панели быстрой закупки с помощью кнопки быстрой покупки

**Comment by ark120202** [comment]
1. Hotkeys are working, but always bound to default values (F5 for quick buy). For now, there is no way to fix it.
2. There is no special delay. For me it works instantly. Perhaps it's caused by lots of calculations made at the purchase moment. In that case shop refactoring might help, but it's out of my plans for now.
